project_id = "aocjoukjdsoynvbuzvas"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[functions]]
[functions.validate-address]
verify_jwt = false