project_id = "aocjoukjdsoynvbuzvas"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[functions]]
[functions.validate-address]
verify_jwt = false

[[functions]]
[functions.lightbox-parcel]
verify_jwt = false

[[functions]]
[functions.claude-compute]
verify_jwt = false

[[functions]]
[functions.claude-health]
verify_jwt = false

[[functions]]
[functions.gemini-compute]
verify_jwt = false

[[functions]]
[functions.grok-compute]
verify_jwt = false

[[functions]]
[functions.perplexity-compute]
verify_jwt = false

[[functions]]
[functions.skyvern-compute]
verify_jwt = false